name: Release Productive Version

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'     
        required: true

env:
  REGISTRY: ghcr.io
  GITHUB_ACTOR: ${{ github.actor }}
  GITHUB_TOKEN: ${{ github.token }}
  REPO_OWNER: ${{ github.repository_owner }}
  VERSION: ${{ github.event.inputs.version }}

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
  release:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@master
        with:
          ref: ${{ github.ref }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/ahatius/signal-cli-rest-api:latest
            ghcr.io/ahatius/signal-cli-rest-api:${{ github.event.inputs.version }}
